name: Check, Build & Deploy Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  lint-and-build:
    runs-on: ubuntu-latest   # Linux is faster & has Node preinstalled
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs deps
        run: pip install mkdocs mkdocs-material

      - name: Install markdownlint
        run: npm i -g markdownlint-cli2

      - name: Lint Markdown
        run: markdownlint-cli2 "docs/**/*.md"

      - name: Build site (strict)
        run: mkdocs build --strict

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress "site/**/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
